server:
  port: 8081
  servlet:
    context-path: /jellyfish



# 子模块加载 如果使用yml则必须为application开头
# @PropertySource注解只支持properties文件
spring:
  profiles:
    active: activemq,rsingle,oracle,mysql,mybatis,fdfs
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB