spring:
  redis:
    #集群
    cluster:
      nodes: 192.168.83.128:7000,192.168.83.128:7001,192.168.83.128:7002,192.168.83.128:7003,192.168.83.128:7004,192.168.83.128:7005
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        min-idle: 20
        max-idle: 100
    database: 0
    ## 连接超时时间（毫秒）
    timeout: 10000
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

